trike:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10  
  
  joint_1_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - joint_1

