<?xml version="1.0"?>
<robot name="trike" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="body_w" value="1" />
  <xacro:property name="body_l" value="3" />
  <xacro:property name="body_h" value="1" />
  <xacro:property name="wheel_r" value="0.5" />
  <xacro:property name="wheel_l" value="0.1" />

  <!-- Import your model behavior in Gazebo -->
  <xacro:include filename="$(find u05)/model/trike.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find rrbot_description)/urdf/materials.xacro" />

  <!-- Connect to world -->
  <link name="world"/>
  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="body"/>
  </joint>

  <!-- Body -->
  <link name="body">
    <visual>
      <origin xyz="0 0 ${2 * wheel_r}" rpy="0 0 0"/>
      <geometry>
	<box size="${body_w} ${body_l} ${body_h}"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <inertial>
      <mass value="1" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="1e-6" ixz="1e-6" iyy="1e-6" iyz="1e-6" izz="1e-6" />
    </inertial>
  </link>

  <!-- Wheel Front -->
  <link name="wheel_1">
    <visual>
      <origin xyz="0 0 0" rpy="0 ${PI / 2} 0"/>
      <geometry>
	<cylinder radius="${wheel_r}" length="${wheel_l}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <inertial>
      <mass value="0.1" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="1e-6" ixz="1e-6" iyy="1e-6" iyz="1e-6" izz="1e-6" />
    </inertial>
  </link>

  <joint name="joint_1" type="fixed">
    <parent link="body"/>
    <child link="wheel_1"/>
    <origin xyz="0 ${-0.45 * body_l} ${wheel_r}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Wheel Rear 1 -->
  <link name="wheel_2">
    <visual>
      <origin xyz="${-wheel_l / 2} 0 0" rpy="0 ${PI / 2} 0"/>
      <geometry>
        <cylinder radius="${wheel_r}" length="${wheel_l}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <inertial>
      <mass value="0.1" />
      <origin xyz="0 0 ${wheel_r}" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="1e-6" ixz="1e-6" iyy="1e-6" iyz="1e-6" izz="1e-6" />
    </inertial>
  </link>

  <joint name="joint_2" type="fixed">
    <parent link="body"/>
    <child link="wheel_2"/>
    <origin xyz="${-body_w / 2} ${0.45 * body_l} ${wheel_r}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Wheel Rear 2 -->
   <link name="wheel_3">
    <visual>
      <origin xyz="${wheel_l / 2} 0 0" rpy="0 ${PI / 2} 0"/>
      <geometry>
        <cylinder radius="${wheel_r}" length="${wheel_l}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <inertial>
      <mass value="0.1" />
      <origin xyz="0 0 ${wheel_r}" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="1e-6" ixz="1e-6" iyy="1e-6" iyz="1e-6" izz="1e-6" />
    </inertial>
  </link>

  <joint name="joint_3" type="fixed">
    <parent link="body"/>
    <child link="wheel_3"/>
    <origin xyz="${body_w / 2} ${0.45 * body_l} ${wheel_r}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Camera -->
  <link name="camera">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.1 0.1 0.1"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <joint name="joint_camera" type="fixed">
    <axis xyz="0 0 1" />
    <origin xyz="0 ${-0.45 * body_l} ${body_h + wheel_r}" rpy="0 0 ${-PI / 2}"/>
    <parent link="body"/>
    <child link="camera"/>
  </joint>

  <!-- Hokuyo Laser -->
  <link name="laser">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://rrbot_description/meshes/hokuyo.dae"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <joint name="joint_laser" type="fixed">
    <axis xyz="0 0 1" />
    <origin xyz="0 ${-0.45 * body_l} ${body_h + wheel_r + 0.1}" rpy="0 ${PI / 16} ${-PI / 2}"/>
    <parent link="body"/>
    <child link="laser"/>
  </joint>

  <transmission name="tran_1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint_1">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_1">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
</robot>
